retribution_entries = {
	"groups": [{
		"id": "faction_retribution_warcasters",
		"entries": [{
			"selectedFA": 0,
			"id": "Rw02",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warcaster",
			"cost": 6,
			"name": "Dawnlord Vyros"
		}, {
			"selectedFA": 0,
			"id": "RW07",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warcaster",
			"cost": 6,
			"name": "Issyria"
		}, {
			"selectedFA": 0,
			"id": "RW06",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warcaster",
			"cost": 6,
			"name": "Ossyan"
		}, {
			"selectedFA": 0,
			"id": "RW05",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warcaster",
			"cost": 6,
			"name": "Ravyn, Eternal Light"
		}, {
			"selectedFA": 0,
			"id": "RW04",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warcaster",
			"cost": 7,
			"name": "Kaelyssa, Night's Whisper"
		}, {
			"selectedFA": 0,
			"id": "RW03",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warcaster",
			"cost": 5,
			"name": "Garryth, Blade of Retribution"
		}, {
			"selectedFA": 0,
			"id": "RW01",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warcaster",
			"cost": 6,
			"name": "Adeptis Rahn Shyeel"
		}, {
			"selectedFA": 0,
			"id": "Rx02",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warcaster",
			"cost": 5,
			"name": "Vyros, Incissar of the Dawnguard"
		}],
		"logo": "faction_retribution",
		"label": "Warcasters"
	}, {
		"id": "faction_retribution_warjacks",
		"entries": [{
			"selectedFA": 0,
			"id": "RJ08",
			"fa": "U",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 4,
			"name": "Aspis"
		}, {
			"selectedFA": 0,
			"id": "RJ09",
			"fa": "U",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 10,
			"name": "Banshee"
		}, {
			"selectedFA": 0,
			"id": "RJ10",
			"fa": "U",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 9,
			"name": "Daemon"
		}, {
			"selectedFA": 0,
			"id": "RJ01",
			"fa": "U",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 6,
			"name": "Chimera"
		}, {
			"selectedFA": 0,
			"id": "RJ03",
			"fa": "U",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 4,
			"name": "Griffon"
		}, {
			"selectedFA": 0,
			"id": "RJ15",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 6,
			"name": "Moros"
		}, {
			"selectedFA": 0,
			"id": "RJ02",
			"fa": "U",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 5,
			"name": "Gorgon"
		}, {
			"selectedFA": 0,
			"id": "RJ14",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 12,
			"name": "Imperatus"
		}, {
			"selectedFA": 0,
			"id": "RJ05",
			"fa": "U",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 8,
			"name": "Manticore"
		}, {
			"selectedFA": 0,
			"id": "RJ13",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 18,
			"name": "Hyperion"
		}, {
			"selectedFA": 0,
			"id": "RJ04",
			"fa": "U",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 9,
			"name": "Hydra"
		}, {
			"selectedFA": 0,
			"id": "RJ12",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 9,
			"name": "Hypnos"
		}, {
			"selectedFA": 0,
			"id": "RJ07",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 10,
			"name": "Discordia"
		}, {
			"selectedFA": 0,
			"id": "RJ11",
			"fa": "U",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 7,
			"name": "Sphinx"
		}, {
			"selectedFA": 0,
			"id": "RJ06",
			"fa": "U",
			"faction": "faction_retribution",
			"type": "warjack",
			"cost": 10,
			"name": "Phoenix"
		}],
		"logo": "faction_retribution",
		"label": "Warjacks"
	}, {
		"id": "faction_retribution_units",
		"entries": [{
			"min": 6,
			"selectedFA": 0,
			"id": "RU04",
			"max": 10,
			"name": "Houseguard Riflemen",
			"costMax": 8,
			"costMin": 5,
			"fa": "3",
			"faction": "faction_retribution",
			"type": "unit",
			"cost": 5
		}, {
			"selectedFA": 0,
			"id": "RU03",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "unit",
			"cost": 5,
			"name": "House Shyeel Battle Mages"
		}, {
			"min": 6,
			"selectedFA": 0,
			"id": "RU02",
			"max": 10,
			"name": "Dawnguard Sentinels",
			"costMax": 9,
			"costMin": 6,
			"fa": "2",
			"faction": "faction_retribution",
			"type": "unitMarshall",
			"cost": 6
		}, {
			"min": 6,
			"selectedFA": 0,
			"id": "RU01",
			"max": 10,
			"name": "Dawnguard Invictors",
			"costMax": 10,
			"costMin": 6,
			"fa": "2",
			"faction": "faction_retribution",
			"type": "unitMarshall",
			"cost": 6
		}, {
			"min": 6,
			"selectedFA": 0,
			"id": "RU10",
			"max": 10,
			"name": "Mage Hunter Infiltrators",
			"costMax": 8,
			"costMin": 5,
			"fa": "2",
			"faction": "faction_retribution",
			"type": "unit",
			"cost": 5
		}, {
			"selectedFA": 0,
			"id": "RU09",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "unit",
			"cost": 2,
			"name": "Heavy Rifle Team"
		}, {
			"selectedFA": 0,
			"id": "RU08",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "unit",
			"cost": 5,
			"name": "Stormfall Archers"
		}, {
			"min": 6,
			"selectedFA": 0,
			"id": "RU07",
			"max": 10,
			"name": "Houseguard Halberdiers",
			"costMax": 7,
			"costMin": 4,
			"fa": "3",
			"faction": "faction_retribution",
			"type": "unit",
			"cost": 4
		}, {
			"min": 3,
			"selectedFA": 0,
			"id": "RU06",
			"max": 5,
			"name": "Dawnguard Destors",
			"costMax": 11,
			"costMin": 7,
			"fa": "1",
			"faction": "faction_retribution",
			"type": "unit",
			"cost": 7
		}, {
			"min": 6,
			"selectedFA": 0,
			"id": "RU05",
			"max": 10,
			"name": "Mage Hunter Strikeforce",
			"costMax": 8,
			"costMin": 5,
			"fa": "2",
			"faction": "faction_retribution",
			"type": "unit",
			"cost": 5
		}],
		"logo": "faction_retribution",
		"label": "Units"
	}, {
		"id": "faction_retribution_UAs",
		"entries": [{
			"selectedFA": 0,
			"id": "RA06",
			"name": "Riflemen Officer & Standard",
			"fa": "1",
			"faction": "faction_retribution",
			"type": "UA",
			"cost": 2,
			"restricted_to": "RU04"
		}, {
			"selectedFA": 0,
			"id": "RA02",
			"name": "Dawnguard Sentinel Officer & Standard",
			"fa": "1",
			"faction": "faction_retribution",
			"type": "UA",
			"cost": 2,
			"restricted_to": "RU02"
		}, {
			"selectedFA": 0,
			"id": "RA01",
			"name": "Dawnguard Invictor Officer & Standard",
			"fa": "1",
			"faction": "faction_retribution",
			"type": "UA",
			"cost": 2,
			"restricted_to": "RU01"
		}, {
			"selectedFA": 0,
			"id": "RA05",
			"name": "Houseguard Halberdiers Officer & Standard",
			"fa": "1",
			"faction": "faction_retribution",
			"type": "UA",
			"cost": 2,
			"restricted_to": "RU07"
		}, {
			"selectedFA": 0,
			"id": "RA03",
			"name": "Mage Hunter Commander",
			"fa": "1",
			"faction": "faction_retribution",
			"type": "UA",
			"cost": 2,
			"restricted_to": "RU05"
		}],
		"logo": "faction_retribution",
		"label": "Unit Attachments"
	}, {
		"id": "faction_retribution_solos",
		"entries": [{
			"selectedFA": 0,
			"id": "RS12",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "soloJourneyMan",
			"cost": 3,
			"name": "Elara, Tyro of The Third Chamber"
		}, {
			"selectedFA": 0,
			"id": "RS13",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "solo",
			"cost": 2,
			"name": "Houseguard Thane"
		}, {
			"selectedFA": 0,
			"id": "RS10",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "solo",
			"cost": 5,
			"name": "Fane Knight Skeryth Issyen"
		}, {
			"selectedFA": 0,
			"id": "RS01",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "solo",
			"cost": 1,
			"name": "Arcanist"
		}, {
			"selectedFA": 0,
			"id": "RS11",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "solo",
			"cost": 3,
			"name": "House Shyeel Artificer"
		}, {
			"selectedFA": 0,
			"id": "RS02",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "soloMarshall",
			"cost": 2,
			"name": "Dawnguard Scyir"
		}, {
			"selectedFA": 0,
			"id": "RS03",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "solo",
			"cost": 2,
			"name": "Ghost Sniper"
		}, {
			"selectedFA": 0,
			"id": "RS04",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "solo",
			"cost": 2,
			"name": "House Shyeel Magister"
		}, {
			"selectedFA": 0,
			"id": "RS05",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "solo",
			"cost": 2,
			"name": "Mage Hunter Assassin"
		}, {
			"selectedFA": 0,
			"id": "RS06",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "solo",
			"cost": 3,
			"name": "Narn, Mage Hunter of Ios"
		}, {
			"selectedFA": 0,
			"id": "RS07",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "solo",
			"cost": 2,
			"name": "Nayl"
		}, {
			"selectedFA": 0,
			"id": "RS08",
			"fa": "2",
			"faction": "faction_retribution",
			"type": "solo",
			"cost": 4,
			"name": "Dawnguard Destor Thane"
		}, {
			"selectedFA": 0,
			"id": "RA04",
			"name": "Soulless Escort",
			"fa": "3",
			"faction": "faction_retribution",
			"type": "UA",
			"cost": 1,
			"restricted_to": ["RU01", "RU02", "RU03", "RU04", "RU05", "RU06", "RU07", "RU08", "RU09", "RU10"]
		}, {
			"selectedFA": 0,
			"id": "RA07",
			"name": "Eiryss3",
			"fa": "C",
			"faction": "faction_retribution",
			"type": "UA",
			"cost": 3,
			"restricted_to": ["RU05", "RU10"]
		}],
		"logo": "faction_retribution",
		"label": "Solos"
	}]
};
